mercure:
    hubs:
        default:
            url: 'http://127.0.0.1:3000/.well-known/mercure'
            public_url: 'http://127.0.0.1:3000/.well-known/mercure'
            jwt:
                secret: '!ChangeThisMercureHubJWTSecretKey!'
                publish: '*'
